---
#promp example
- name: Host Declaration
  hosts: 127.0.0.1
  connection: local
  gather_facts: false 

  vars_prompt:
    - name: user
      prompt: Enter user Name
      private: no

  tasks:
    - name: Print user values
      shell: "echo {{ user }}"
      register: user

    - debug:
        msg: "{{ user['stdout_lines'] }}"
